[project]
name = "sre-copilot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "langchain>=1.0.5",
    "langchain-milvus>=0.2.2",
    "python-dotenv>=1.2.1",
]
